name: Upstream
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: 1
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      - name: Load the upstream packages and run the tests
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.Registry.update()
          Pkg.activate(;temp=true)
          # force it to use this PR's version of the package
          ENV["JULIA_PKG_DEVDIR"]= mktempdir()
          Pkg.develop([
            PackageSpec(path="."),
            PackageSpec(name="TranscodingStreams"),
          ])
          Pkg.update()
          Pkg.test("CodecZstd"; coverage=true)
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
